spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate

SECRET_ENCRYPTION_PHRASE: ${SECRET_ENCRYPTION_PHRASE}
JWT_SECRET: ${JWT_SECRET}
ACCESS_TTL: 900000
REFRESH_TTL: 604800000
