spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
